# conda environment description file for readthedocs build environment

name: {{ cookiecutter.package_name.lower() }}-rtd

channels:
  - defaults

dependencies:
  - python={{ cookiecutter.dev_python_version }}

  # RTD packages
  - mock
  - pillow
  - sphinx
  - sphinx_rtd_theme
